### ISSUE TITLE
Linux build / Source Code

### ISSUE THREAD

**Issue by dror-g** [KumologicaHQ/kumologica-designer-releases#1]
Hi, I know a Linux build might be too much to ask for in this early stage, 
But perhaps the source code could be made available in a more convenient form?
As I understand this is a Node + Electron app so in theory should be able to run on Linux.
Thanks!

**Comment by bjq-dev** [comment]
Hi Dror, thanks for your interest in kumologica, you are right, its node + electron app, we started work on linux build as we noticed interest from the community. If you wish to be notified about pre-release linux bundle, please drop us contact details to https://kumologica.com/contact.html and we will notify you once we publish. 
Cheers

**Comment by bjq-dev** [comment]
Linux builds published in 0.9.3, AppImage and deb. Builds currently accessible via git releases only.
